### ISSUE TITLE
ImportError: No module named BeautifulSoup

### ISSUE THREAD

**Issue by autumnwalker** [mklips0/envisakit#1]
When trying to run ./envisakit-cli status I am getting the following error:

Using EZMobile interface...
Traceback (most recent call last):
  File "./envisakit.py", line 3, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

When I download BeautifulSoup via apt (Ubuntu 14.04 LTS) and comment out the virtualenv in envisakit-cli the issue goes away. Any reason you're using virtualenv?

**Comment by mklips0** [comment]
I use virtualenv because I did not want to require anyone to install BeautifulSoup globally. If you don't want to use virtualenv, you could also navigate into the cli directory and run ./envisakit.py directly.

**Comment by autumnwalker** [comment]
Understood!

Any thoughts on the error I am receiving when trying to run with virtualenv?

**Comment by mklips0** [comment]
Did you run the following commands to set up the virtualenv? 

Make sure that when you run these commands, you are in the root directory of the project. It should create a new "venv" directory, alongside "cli".

```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by autumnwalker** [comment]
Yup! I see the folder venv along with cli under "/usr/src/envisakit".

**Comment by mklips0** [comment]
After running `source venv/bin/activate`, what is the output of `pip freeze`?

**Comment by autumnwalker** [comment]
argparse==1.2.1
wsgiref==0.1.2

**Comment by mklips0** [comment]
For some reason it looks like BeautifulSoup is not being correctly installed in your virtualenv. If it were, `pip freeze` should show something like `BeautifulSoup==3.2.1`. 

After running `source venv/bin/activate` (if you aren't seeing the `(venv)` on your prompt), can you show me the output of `pip install -r requirements.txt`? Maybe there is an error in there?

**Comment by autumnwalker** [comment]
Downloading/unpacking BeautifulSoup==3.2.1 (from -r requirements.txt (line 1))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/src/envisakit/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/src/envisakit/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/src/envisakit/venv/local/lib/python2.7/site-packages/pip/req.py", line 1153, in prepare_files
    location = req_to_install.build_location(self.build_dir, not self.is_download)
  File "/usr/src/envisakit/venv/local/lib/python2.7/site-packages/pip/req.py", line 218, in build_location
    _make_build_dir(build_dir)
  File "/usr/src/envisakit/venv/local/lib/python2.7/site-packages/pip/req.py", line 1527, in _make_build_dir
    os.makedirs(build_dir)
  File "/usr/src/envisakit/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/src/envisakit/venv/build'

Storing debug log for failure in /home/<username>/.pip/pip.log

If I run as sudo pip install -r requirements.txt I get:

Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup==3.2.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Cleaning up...

**Comment by autumnwalker** [comment]
Directory / file ownership error. I should have known.

running `sudo chown -R user:group envisakit` allowed me to run `pip install -r requirements.txt` and then no issue running `./envisakit-cli`.

Thanks!
